import type { Metadata } from "next";
import { kanit, montserrat } from "@/app/ui/fonts"
import "./globals.css";

export const metadata: Metadata = {
  title: "CS 180 Project",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${montserrat.className} antialiased bg-gradient-to-tr from-slate-900 from-60% to-black`}>{children}</body>
    </html>
  );
}
